import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Attestix by VibeTensor Private Limited.",
};

export default function TermsOfService() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p className="text-muted-foreground">
        Last updated: February 27, 2026
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By accessing or using the Attestix website (attestix.io) or
        the Attestix software, you agree to be bound by these Terms of Service.
        If you do not agree, do not use our services.
      </p>

      <h2>2. About Attestix</h2>
      <p>
        Attestix is an open-source attestation infrastructure for AI agents,
        developed and maintained by VibeTensor Private Limited. The software is
        distributed under the Apache License 2.0.
      </p>

      <h2>3. Use of the Software</h2>
      <h3>3.1 Open Source License</h3>
      <p>
        The Attestix software is licensed under the Apache License, Version 2.0.
        You may use, modify, and distribute the software in accordance with the
        terms of that license. The full license text is available at{" "}
        <a
          href="https://github.com/VibeTensor/attestix/blob/main/LICENSE"
          target="_blank"
          rel="noopener noreferrer"
        >
          github.com/VibeTensor/attestix/blob/main/LICENSE
        </a>
        .
      </p>
      <h3>3.2 Acceptable Use</h3>
      <p>You agree not to:</p>
      <ul>
        <li>Use the software for any unlawful purpose</li>
        <li>
          Misrepresent the source or origin of attestations, credentials, or
          identity documents generated by the software
        </li>
        <li>
          Use the software to create fraudulent compliance declarations or
          certifications
        </li>
        <li>
          Attempt to circumvent security measures or exploit vulnerabilities
        </li>
        <li>
          Impersonate any person or entity through generated identity artifacts
        </li>
      </ul>

      <h2>4. Enterprise Services</h2>
      <p>
        Enterprise support services are governed by separate agreements. Contact
        info@vibetensor.com for enterprise inquiries.
      </p>

      <h2>5. Disclaimer of Warranties</h2>
      <p>
        THE SOFTWARE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;
        WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
        LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, AND NONINFRINGEMENT.
      </p>
      <p>
        Attestix provides tools for generating compliance-related documentation
        artifacts such as signed declarations and verifiable credentials. These
        tools do not constitute legal advice, regulatory certification, or
        official compliance proof. Use of the software does not guarantee
        regulatory compliance with the EU AI Act or any other regulation. You
        are solely responsible for ensuring that your AI systems meet applicable
        regulatory requirements. Always consult qualified legal professionals
        for compliance decisions.
      </p>

      <h2>6. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, VIBETENSOR PRIVATE
        LIMITED SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES,
        WHETHER INCURRED DIRECTLY OR INDIRECTLY, ARISING OUT OF YOUR USE OF THE
        SOFTWARE OR WEBSITE.
      </p>

      <h2>7. Indemnification</h2>
      <p>
        You agree to indemnify and hold harmless VibeTensor Private Limited from
        any claims, damages, or expenses arising from your violation of these
        terms, your unlawful use of the software, or any third-party claims
        resulting from artifacts you generate using Attestix.
      </p>

      <h2>8. Intellectual Property</h2>
      <p>
        The Attestix name, logo, and brand assets are trademarks of VibeTensor
        Private Limited. The software source code is licensed under Apache 2.0.
        Third-party components retain their respective licenses.
      </p>

      <h2>9. Third-Party Links</h2>
      <p>
        Our website may contain links to third-party websites (GitHub, PyPI, MCP
        Registry). We are not responsible for the content or practices of these
        external sites.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These Terms shall be governed by and construed in accordance with the
        laws of India. Any disputes arising out of these Terms shall be subject
        to the exclusive jurisdiction of the courts in Hyderabad, Telangana,
        India.
      </p>

      <h2>11. Changes to Terms</h2>
      <p>
        We may revise these Terms at any time by posting updates on this page.
        Continued use of the website or software after changes constitutes
        acceptance of the revised terms.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these Terms of Service, contact us at
        info@vibetensor.com.
      </p>
    </>
  );
}
